name: PaperBridge
options:
  bundleIdPrefix: com.yuka
targets:
  PaperBridge:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 14.0
    sources: [PaperBridge]
    settings:
      CODE_SIGN_IDENTITY: iPhone Developer
      DEVELOPMENT_TEAM: 8J78YW46G6
      INFOPLIST_FILE: PaperBridge/Application/Info.plist
      SUPPORTS_MACCATALYST: true
      SWIFT_VERSION: 5.3
    prebuildScripts:
      - name: Run SwiftLint
        script: |
                if mint which swiftlint >/dev/null; then
                mint run swiftlint autocorrect --format
                mint run swiftlint
                else
                echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
  PaperBridgeTests:
    type: bundle.unit-test
    platform: iOS
    sources: PaperBridgeTests
    dependencies:
      - target: PaperBridge
  PaperBridgeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: PaperBridgeUITests
    dependencies:
      - target: PaperBridge
